// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  production: false,
  
  //Dev
  live_url: 'https://fcmdev.thestorywallcafe.com',
  lead_list:'https://fcmdev.thestorywallcafe.com/api/lead-list/',
  lead_status:'https://fcmdev.thestorywallcafe.com/api/lead-list-status/',
  lead_subStatus:'https://fcmdev.thestorywallcafe.com/api/lead-list-substatus/',
  lead_season:'https://fcmdev.thestorywallcafe.com/api/season/',
  lead_priority:'https://fcmdev.thestorywallcafe.com/api/priority/',
  lead_campaign:'https://fcmdev.thestorywallcafe.com/api/campaign-lead-list/',
  lead_course:'https://fcmdev.thestorywallcafe.com/api/course-leadlist/',
  lead_upload:'https://fcmdev.thestorywallcafe.com/api/upload-lead-data/',
  lead_refer:'https://fcmdev.thestorywallcafe.com/api/refer-lead-counsellor/',
  lead_note:'https://fcmdev.thestorywallcafe.com/api/note/',
  _user:'https://fcmdev.thestorywallcafe.com/api/user/',
  lead_email:'https://fcmdev.thestorywallcafe.com/api/send-emails/',
  raw_data:'https://fcmdev.thestorywallcafe.com/api/upload-lead-data/',
  lead_ids:`https://fcmdev.thestorywallcafe.com/api/get-lead-ids/`,
  whatsapp_template:`https://fcmdev.thestorywallcafe.com/api/template/`,
  lead_follow_up:`https://fcmdev.thestorywallcafe.com/api/follow-up/`,
  export_leads:`https://fcmdev.thestorywallcafe.com/api/export-leads/`,
  leadPayment:`https://fcmdev.thestorywallcafe.com/api/send-payment-link/`,
  paymentDetails:`https://fcmdev.thestorywallcafe.com/api/payment-details/`,
  leadStage:`https://fcmdev.thestorywallcafe.com/api/lead-stage/`,
  admission_details:`https://fcmdev.thestorywallcafe.com/api/admission-details/`,
  followUps:`https://fcmdev.thestorywallcafe.com/api/follow-up/`,
  payment_status:`https://fcmdev.thestorywallcafe.com/api/payment-status/`,
  studying_stream:`https://fcmdev.thestorywallcafe.com/api/studying-stream/`,
  reports:`https://fcmdev.thestorywallcafe.com/api/get-reports/`

 //Test
  // live_url:'https://fcmtest.thestorywallcafe.com',
  // lead_list:'https://fcmtest.thestorywallcafe.com/api/lead-list/',
  // lead_status:'https://fcmtest.thestorywallcafe.com/api/lead-list-status/',
  // lead_subStatus:'https://fcmtest.thestorywallcafe.com/api/lead-list-substatus/',
  // lead_season:'https://fcmtest.thestorywallcafe.com/api/season/',
  // lead_priority:'https://fcmtest.thestorywallcafe.com/api/priority/',
  // lead_campaign:'https://fcmtest.thestorywallcafe.com/api/campaign-lead-list/',
  // lead_course:'https://fcmtest.thestorywallcafe.com/api/course-leadlist/',
  // lead_upload:'https://fcmtest.thestorywallcafe.com/api/upload-lead-data/',
  // lead_refer:'https://fcmtest.thestorywallcafe.com/api/refer-lead-counsellor/',
  // lead_note:'https://fcmtest.thestorywallcafe.com/api/note/',
  // _user:'https://fcmtest.thestorywallcafe.com/api/user/',
  // lead_email:'https://fcmtest.thestorywallcafe.com/api/send-emails/',
  // raw_data:'https://fcmtest.thestorywallcafe.com/api/upload-lead-data/',
  // lead_ids:`https://fcmtest.thestorywallcafe.com/api/get-lead-ids/`,
  // whatsapp_template:`https://fcmtest.thestorywallcafe.com/api/template/`,
  // lead_follow_up:`https://fcmtest.thestorywallcafe.com/api/follow-up/`,
  // export_leads:`https://fcmtest.thestorywallcafe.com/api/export-leads/`,
  // leadPayment:`https://fcmtest.thestorywallcafe.com/api/send-payment-link/`,
  // paymentDetails:`https://fcmtest.thestorywallcafe.com/api/payment-details/`,
  // leadStage:`https://fcmtest.thestorywallcafe.com/api/lead-stage/`,
  // admission_details:`https://fcmtest.thestorywallcafe.com/api/admission-details/`,
  // followUps:`https://fcmtest.thestorywallcafe.com/api/follow-up/`,
  // payment_status:`https://fcmtest.thestorywallcafe.com/api/payment-status/`,
  // studying_stream:`https://fcmtest.thestorywallcafe.com/api/studying-stream/`,
  // reports:`https://fcmtest.thestorywallcafe.com/api/get-reports/`
  
  //Docker
  // live_url:'http://localhost:8005',
  // lead_list:'http://localhost:8005/api/lead-list/',
  // lead_status:'http://localhost:8005/api/lead-list-status/',
  // lead_subStatus:'http://localhost:8005/api/lead-list-substatus/',
  // lead_season:'http://localhost:8005/api/season/',
  // lead_priority:'http://localhost:8005/api/priority/',
  // lead_campaign:'http://localhost:8005/api/campaign-lead-list/',
  // lead_course:'http://localhost:8005/api/course-leadlist/',
  // lead_upload:'http://localhost:8005/api/upload-lead-data/',
  // lead_refer:'http://localhost:8005/api/refer-lead-counsellor/',
  // lead_note:'http://localhost:8005/api/note/',
  // _user:'http://localhost:8005/api/user/',
  // lead_email:'http://localhost:8005/api/send-emails/',
  // raw_data:'http://localhost:8005/api/upload-lead-data/',
  // lead_ids:`http://localhost:8005/api/get-lead-ids/`,
  // whatsapp_template:`http://localhost:8005/api/template/`,
  // lead_follow_up:`http://localhost:8005/api/follow-up/`,
  // export_leads:`http://localhost:8005/api/export-leads/`,
  // leadPayment:`http://localhost:8005/api/send-payment-link/`,
  // paymentDetails:`http://localhost:8005/api/payment-details/`,
  // leadStage:`http://localhost:8005/api/lead-stage/`,
  // admission_details:`http://localhost:8005/api/admission-details/`,
  // followUps:`http://localhost:8005/api/follow-up/`,
  // payment_status:`http://localhost:8005/api/payment-status/`,
  // studying_stream:`http://localhost:8005/api/studying-stream/`,
  // reports:`http://localhost:8005/api/get-reports/`

  //Admin
  // live_url:'https://admin.firstclassmentor.com',
  // lead_list:'https://admin.firstclassmentor.com/api/lead-list/',
  // lead_status:'https://admin.firstclassmentor.com/api/lead-list-status/',
  // lead_subStatus:'https://admin.firstclassmentor.com/api/lead-list-substatus/',
  // lead_season:'https://admin.firstclassmentor.com/api/season/',
  // lead_priority:'https://admin.firstclassmentor.com/api/priority/',
  // lead_campaign:'https://admin.firstclassmentor.com/api/campaign-lead-list/',
  // lead_course:'https://admin.firstclassmentor.com/api/course-leadlist/',
  // lead_upload:'https://admin.firstclassmentor.com/api/upload-lead-data/',
  // lead_refer:'https://admin.firstclassmentor.com/api/refer-lead-counsellor/',
  // lead_note:'https://admin.firstclassmentor.com/api/note/',
  // _user:'https://admin.firstclassmentor.com/api/user/',
  // lead_email:'https://admin.firstclassmentor.com/api/send-emails/',
  // raw_data:'https://admin.firstclassmentor.com/api/upload-lead-data/',
  // lead_ids:`https://admin.firstclassmentor.com/api/get-lead-ids/`,
  // whatsapp_template:`https://admin.firstclassmentor.com/api/template/`,
  // lead_follow_up:`https://admin.firstclassmentor.com/api/follow-up/`,
  // export_leads:`https://admin.firstclassmentor.com/api/export-leads/`,
  // leadPayment:`https://admin.firstclassmentor.com/api/send-payment-link/`,
  // paymentDetails:`https://admin.firstclassmentor.com/api/payment-details/`,
  // leadStage:`https://admin.firstclassmentor.com/api/lead-stage/`,
  // admission_details:`https://admin.firstclassmentor.com/api/admission-details/`,
  // followUps:`https://admin.firstclassmentor.com/api/follow-up/`,
  // payment_status:`https://admin.firstclassmentor.com/api/payment-status/`,
  // studying_stream:`https://admin.firstclassmentor.com/api/studying-stream/`,
  // reports:`https://admin.firstclassmentor.com/api/get-reports/`
};
