export const environment = {
  production: true,
  live_url: 'https://fcmdev.thestorywallcafe.com',
  lead_list:'/api/lead-list/',
  lead_status:'/api/lead-list-status/',
  lead_subStatus:'/api/lead-list-substatus/',
  lead_season:'/api/season/',
  lead_priority:'/api/priority/',
  lead_campaign:'/api/campaign-lead-list/',
  lead_course:'/api/course-leadlist/',
  lead_upload:'/api/upload-lead-data/',
  lead_refer:'/api/refer-lead-counsellor/',
  lead_note:'/api/note/',
  _user:'/api/user',
  lead_email:'/api/send-emails/',
  raw_data:'/api/upload-lead-data/',
  lead_ids:`/api/get-lead-ids/`,
  whatsapp_template:`/api/template/`,
  lead_follow_up:`/api/follow-up/`,
  export_leads:`/api/export-leads/`,
  leadPayment:`/api/send-payment-link/`,
  paymentDetails:`/api/payment-details/`
};
